site_name:           OITOOLS.jl
repo_url:            https://github.com/fabienbaron/OITOOLS.jl
site_description:    OITOOLS
site_author:         Fabien Baron
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
#  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

nav:
- Introduction: index.md
- Installation: install.md
- Examples: examples.md
